services:
  db:
    image: docker.arvancloud.ir/mysql:8.0
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - ./mysql:/var/lib/mysql
    networks:
      - app-network
    dns:
      - 185.51.200.2
      - 178.22.122.100

  backend:
    build: ./backend
    container_name: fastapi_backend
    environment:
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      SECRET_KEY: ${SECRET_KEY}
      NEXTCLOUDWEBSITE: ${NEXTCLOUDWEBSITE}
      NEXTCLOUDUSERNAME: ${NEXTCLOUDUSERNAME}
      NEXTCLOUDPASSWORD: ${NEXTCLOUDPASSWORD}
    depends_on:
      - db
    volumes:
      - ./backend/uploads:/app/uploads
    networks:
      - app-network
    dns:
      - 185.51.200.2
      - 178.22.122.100

  frontend:
    build: ./ui
    container_name: react_frontend
    volumes:
      - ./ui/build:/app/dist
    networks:
      - app-network
    depends_on:
      - backend
    dns:
      - 185.51.200.2
      - 178.22.122.100

  nginx:
    image: docker.arvancloud.ir/nginx:alpine
    container_name: nginx_proxy
    environment:
      - DOMAIN=${DOMAIN}
    ports:
      - "801:80"
      - "4431:443"
    volumes:
      - ./nginx/templates:/etc/nginx/templates
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
      - ./ui/build:/usr/share/nginx/html
    depends_on:
      - frontend
    networks:
      - app-network
#    dns:
#      - 185.51.200.2
#      - 178.22.122.100

  certbot:
    image: docker.arvancloud.ir/certbot/certbot
    container_name: certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge